- umh.docs.umh.app/content/en/docs/architecture/microservices/community/barcodereader.md
fixed documentation in barcodereader
> changed mqtt to kafka

- .github/ISSUE_TEMPLATE/bug-report.yaml
- .github/ISSUE_TEMPLATE/feature-request.yaml
- .github/pull_request_template.md
Restyling of issues and pr templates.
Fixes #68 
What types of changes does your code introduce to this project?
> Improve issue templates

- umh.docs.umh.app/content/en/docs/architecture/datamodel/messages/uniqueProduct.md
> Updated the example to fix the bool<-> string discrepancy for IsScrap

- umh.docs.umh.app/content/en/docs/architecture/helm-chart.md
- umh.docs.umh.app/content/en/docs/production-guide/administration/change-factoryinsight-language.md
- umh.docs.umh.app/content/en/docs/production-guide/installation/local-k3d-installation.md
This pr removes dead links to the customization page.
Closes #114
> Remove reference to missing customization page

- umh.docs.umh.app/content/en/docs/architecture/helm-chart.md
- umh.docs.umh.app/content/en/docs/production-guide/upgrading/0.9.13.md
- umh.docs.umh.app/content/en/docs/whatsnew/0.9.13.md
- umh.docs.umh.app/content/en/docs/whatsnew/_index.md
- umh.docs.umh.app/hugo.toml
- umh.docs.umh.app/i18n/en/en.toml
This PR releases the new documentation for version 0.9.12
> Release v0.9.13

- Makefile
This PR adds an help target and improves the documentation for the Makefile
> Add help target and improve documentation for Makefile

- umh.docs.umh.app/content/en/docs/features/barcodereader-retrofitting/index.md
- umh.docs.umh.app/content/en/docs/features/data-connectivity-node-red/index.md
- umh.docs.umh.app/content/en/docs/features/ifm-retrofitting/index.md
- umh.docs.umh.app/content/en/docs/features/postgresql_and_grafana_alerts.md
> fix: feature descriptions

- umh.docs.umh.app/content/en/docs/production-guide/upgrading/0.9.14.md
- umh.docs.umh.app/content/en/docs/whatsnew/0.9.10.md
- umh.docs.umh.app/content/en/docs/whatsnew/0.9.11.md
- umh.docs.umh.app/content/en/docs/whatsnew/0.9.14.md
- umh.docs.umh.app/content/en/docs/whatsnew/_index.md
This PR adds the upgrading instructions and the what's new page for version 0.9.14
> Upgrade to 0.9.14

- umh.docs.umh.app/content/en/docs/production-guide/installation/flatcar-installation-bare-metal.md
- umh.docs.umh.app/content/en/docs/production-guide/installation/flatcar-installation-virtual-machine.md
Added notice that instaallation may take a while
See also: https://github.com/orgs/united-manufacturing-hub/projects/7/views/1?pane=issue&itemId=28186094
> feat: added notice that installation may take a while

- umh.docs.umh.app/content/en/docs/getstarted/managingthesystem.md
- umh.docs.umh.app/content/en/docs/production-guide/installation/flatcar-installation-bare-metal.md
- umh.docs.umh.app/content/en/docs/production-guide/installation/flatcar-installation-virtual-machine.md
- umh.docs.umh.app/content/en/includes/task-befinst-prereqs.md
Updates to the Documentation: Spelling, old system requirements and missing info
> fix: correct system requirements for VM installation

- umh.docs.umh.app/hugo.toml
> feat: update branch in hugo conf

- umh.docs.umh.app/content/en/docs/getstarted/dataacquisitionmanipulation.md
- umh.docs.umh.app/content/en/docs/getstarted/datavisualization.md
- umh.docs.umh.app/static/images/getstarted/dataAcquisitionManipulation/usefulInfoMgmt.png
Our getting started section wasn't aligned with the mgmt console. 
I removed the lens part and updated it to fit to the current mgmt console.
> getting started, adjusted for mgmt console

- README.md
- umh.docs.umh.app/content/en/docs/development/contribute/documentation/setup-environment.md
- umh.docs.umh.app/content/en/docs/development/contribute/new-content/add-documentation.md
Addresses the issues I discovered while setting up my own local environment to make documentation contributions.
Fixes #152 
> made changes related to the issue discussion

- umh.docs.umh.app/archetypes/feature.md
- umh.docs.umh.app/content/en/docs/features/connectivity/additionalconnectivity/_index.md
This PR enables pages that have been mistakenly set to draft
It also add the archetype for the Feature section
> Enable drafts

- umh.docs.umh.app/content/en/docs/architecture/data-infrastructure/data-connectivity/barcodereader.md
- umh.docs.umh.app/content/en/docs/architecture/data-infrastructure/data-connectivity/node-red.md
- umh.docs.umh.app/content/en/docs/architecture/data-infrastructure/data-connectivity/sensorconnect.md
- umh.docs.umh.app/content/en/docs/architecture/data-infrastructure/historian/cache.md
- umh.docs.umh.app/content/en/docs/architecture/data-infrastructure/historian/database.md
- umh.docs.umh.app/content/en/docs/architecture/data-infrastructure/historian/factoryinsight.md
- umh.docs.umh.app/content/en/docs/architecture/data-infrastructure/historian/grafana.md
- umh.docs.umh.app/content/en/docs/architecture/data-infrastructure/historian/umh-datasource-v2.md
- umh.docs.umh.app/content/en/docs/architecture/data-infrastructure/unified-namespace/data-bridge.md
- umh.docs.umh.app/content/en/docs/architecture/data-infrastructure/unified-namespace/kafka-broker.md
- umh.docs.umh.app/content/en/docs/architecture/data-infrastructure/unified-namespace/kafka-console.md
- umh.docs.umh.app/content/en/docs/architecture/data-infrastructure/unified-namespace/mqtt-broker.md
- umh.docs.umh.app/content/en/docs/architecture/legacy/factoryinput.md
- umh.docs.umh.app/content/en/docs/architecture/legacy/grafana-proxy.md
- umh.docs.umh.app/content/en/docs/architecture/legacy/kafka-bridge.md
- umh.docs.umh.app/content/en/docs/architecture/legacy/kafka-state-detector.md
- umh.docs.umh.app/content/en/docs/architecture/legacy/kafka-to-postgresql.md
- umh.docs.umh.app/content/en/docs/architecture/legacy/mqtt-bridge.md
- umh.docs.umh.app/content/en/docs/architecture/legacy/mqtt-kafka-bridge.md
- umh.docs.umh.app/content/en/docs/architecture/legacy/mqtt-simulator.md
- umh.docs.umh.app/content/en/docs/architecture/legacy/mqtt-to-postgresql.md
- umh.docs.umh.app/content/en/docs/architecture/legacy/opcua-simulator.md
- umh.docs.umh.app/content/en/docs/architecture/legacy/packml-simulator.md
- umh.docs.umh.app/content/en/docs/architecture/legacy/tulip-connector.md
- umh.docs.umh.app/content/en/docs/reference/helm-chart.md
- umh.docs.umh.app/content/en/docs/reference/microservices/data-bridge.md
This PR adjust some aliases and updates some broken links
Fix https://github.com/united-manufacturing-hub/MgmtIssues/issues/1179
> Fix broken links

- umh.docs.umh.app/content/en/docs/getstarted/datavisualization.md
Related to https://github.com/united-manufacturing-hub/ManagementConsole/pull/254
> Added plc13

- umh.docs.umh.app/content/en/docs/getstarted/dataacquisitionmanipulation.md
- Deleted unknown characters in a sentence.
- Deleted the default port of OPC-UA.
closes united-manufacturing-hub/MgmtIssues/issues/1207
> Minor fix in Data Acquisition and Manipulation

- umh.docs.umh.app/content/en/docs/concepts/security/device-and-container-infrastructure.md
This PR adds the documentation regarding the security of the Device & Container Infrastructure. The page is set to draft, as per requirement. For the same reason, it is not very detailed
Close https://github.com/united-manufacturing-hub/MgmtIssues/issues/1434
> Add Device & Container Infrastructure security documentation

- umh.docs.umh.app/content/en/docs/concepts/security/data-infrastructure.md
This PR adds the documentation regarding the security of the Data Infrastructure. The page is set to draft, as per requirement. For the same reason, it is not very detailed
Close https://github.com/united-manufacturing-hub/MgmtIssues/issues/1433
> Add Data Infrastructure security documentation

- umh.docs.umh.app/content/en/docs/features/connectivity/benthos-umh.md
- umh.docs.umh.app/content/en/docs/getstarted/dataacquisitionmanipulation.md
https://github.com/united-manufacturing-hub/MgmtIssues/issues/1231
> Update field name from 'useCase' to 'schema' in OPC UA configuration

- umh.docs.umh.app/content/en/docs/concepts/_index.md
- umh.docs.umh.app/content/en/docs/concepts/security/_index.md
- umh.docs.umh.app/content/en/docs/concepts/security/management-console.md
This PR adds the documentation regarding the security of the Management Console
Close https://github.com/united-manufacturing-hub/MgmtIssues/issues/1432
> Add security for Management Console concept page

- .gitpod.yml
- umh.docs.umh.app/content/en/docs/development/contribute/united-manufacturing-hub/release-process.md
Closes https://github.com/united-manufacturing-hub/MgmtIssues/issues/1459
> Added companion release process details

- umh.docs.umh.app/content/en/docs/production-guide/upgrading/upgrading.md
- umh.docs.umh.app/content/en/docs/whatsnew/0.2.md
This PR adds the What's New page for version 0.2, along with the upgrading instructions from previous versions
> Add What's New in version 0.2

- umh.docs.umh.app/content/en/docs/features/devicecontainerinfrastructure/monitoring.md
Fix https://github.com/united-manufacturing-hub/MgmtIssues/issues/1475
> Add link to Connectivity section in Connection Management paragraph

- umh.docs.umh.app/content/en/docs/production-guide/upgrading/archive/0.9.34.md
Close https://github.com/united-manufacturing-hub/MgmtIssues/issues/1474
> Upgrade UMH to v0.9.34

- umh.docs.umh.app/content/en/docs/development/contribute/united-manufacturing-hub/release-process.md
This PR adds the testing process to be executed before releasing a new version
> Add testing process for new version release

- umh.docs.umh.app/content/en/docs/production-guide/upgrading/archive/0.9.34.md
This PR fixes the upgrade process for umh version 0.9.34
Fix https://github.com/united-manufacturing-hub/MgmtIssues/issues/1491
> Fix update database step in v0.9.34 upgrade guide

- umh.docs.umh.app/content/en/docs/production-guide/upgrading/upgrading.md
- umh.docs.umh.app/content/en/docs/whatsnew/0.1.md
- umh.docs.umh.app/content/en/docs/whatsnew/0.2.md
This PR add the patch notes for version 0.2.1. Additionally, fixes the patch notes for previous versions
> Patch notes 0.2.1

- umh.docs.umh.app/content/en/docs/whatsnew/0.2.md
https://github.com/united-manufacturing-hub/ManagementConsole/pull/333
> Patch notes 0.2.2

- umh.docs.umh.app/content/en/docs/whatsnew/0.2.md
> Version 0.2.3

- umh.docs.umh.app/content/en/docs/production-guide/upgrading/archive/0.10.6.md
> Upgrade UMH to v0.10.6

- umh.docs.umh.app/content/en/docs/getstarted/dataacquisitionmanipulation.md
Fixing a broken link in the section "3. Data Acquisition and Manipulation".
> fix typo in datamodel path

- umh.docs.umh.app/content/en/docs/development/contribute/united-manufacturing-hub/release-process.md
Added external image overwrite validation section to release guide
> Added external image overwrite validation section to release guide

- umh.docs.umh.app/content/en/docs/whatsnew/0.2.md
This pr is the documentation for the 0.2.4 release
> feat: 0.2.4

- umh.docs.umh.app/content/en/docs/whatsnew/0.2.md
Documentation for the 0.2.5 release
> feat: 0.2.5

- umh.docs.umh.app/content/en/docs/production-guide/administration/normalize-kafka-topics.md
- umh.docs.umh.app/i18n/en/en.toml
Add documentation for normalizing Kafka topics
Close https://github.com/united-manufacturing-hub/MgmtIssues/issues/959
> Add documentation for normalizing Kafka topics

- umh.docs.umh.app/content/en/docs/whatsnew/0.2.md
- Close https://github.com/united-manufacturing-hub/MgmtIssues/issues/1609
> Add patch notes 0.2.8

- umh.docs.umh.app/content/en/docs/production-guide/upgrading/migrate-to-data-model-v1.md
Close https://github.com/united-manufacturing-hub/MgmtIssues/issues/982
> Add migration guide for Data Model V1

- .github/workflows/link-checker.yml
- .gitignore
- find-dead.py
- umh.docs.umh.app/content/en/docs/datamodel_old/states/_index.md
This pr resolves a dead link in status and adds a small script to find more
> Resolve dead link and add finder script

- umh.docs.umh.app/content/en/docs/features/datainfrastructure/unified-namespace.md
- umh.docs.umh.app/content/en/docs/getstarted/datavisualization.md
- umh.docs.umh.app/static/images/features/unified-namespace/tagBrowser.png
This PR updates the listed tag browser's features in the unified namespace page to also contain the new sql query generation feature.
- Closes https://github.com/united-manufacturing-hub/MgmtIssues/issues/1708
> Mention the new sql query generation feature of the tag browser

- umh.docs.umh.app/content/en/docs/getstarted/datavisualization.md
- umh.docs.umh.app/static/images/features/unified-namespace/tagBrowser.png
This PR optimizes the SQL query provided in the data visualization step of the get started guide. It now uses built-in grafana variables and functions such as `$__interval` and `$__timeFilter`, as well as the `time_bucket` timescaleDB function.
Each part is explained and links to the corresponding docs,
- Closes https://github.com/united-manufacturing-hub/MgmtIssues/issues/1656
> Refactor the data visualization query and document each of its components

- umh.docs.umh.app/content/en/docs/datamodel/messages/_analytics.md
- umh.docs.umh.app/content/en/docs/datamodel/states/_index.md
- umh.docs.umh.app/content/en/docs/datamodel/states/active.md
- umh.docs.umh.app/content/en/docs/datamodel/states/material.md
- umh.docs.umh.app/content/en/docs/datamodel/states/operator.md
- umh.docs.umh.app/content/en/docs/datamodel/states/planning.md
- umh.docs.umh.app/content/en/docs/datamodel/states/process.md
- umh.docs.umh.app/content/en/docs/datamodel/states/technical.md
- umh.docs.umh.app/content/en/docs/datamodel/states/unknown.md
Closes https://github.com/united-manufacturing-hub/MgmtIssues/issues/1618
> Analytics page (message changes & states)

- .github/pull_request_template.md
> Fix the link to Code of Conduct in PR template

- umh.docs.umh.app/content/en/docs/getstarted/installation.md
Fix a typo Operaing -> Operating.
> (fix): Minor typo in Installation page

- .github/pull_request_template.md
- umh.docs.umh.app/content/en/docs/getstarted/installation.md
> Rebase main

- umh.docs.umh.app/content/en/docs/features/devicecontainerinfrastructure/monitoring.md
> Minor text fixes

- umh.docs.umh.app/content/en/docs/whatsnew/0.2.md
See also https://github.com/united-manufacturing-hub/ManagementConsole/pull/657
> feat: 0.2.17

- umh.docs.umh.app/content/en/docs/whatsnew/0.2.md
This PR just adds some missing information to the changelogs of `0.2.16` and `0.2.17`.
> Add missing changelog data to 0.2.16 and 0.2.17

- umh.docs.umh.app/content/en/docs/whatsnew/0.2.md
Release notes for 0.2.18.
See also https://github.com/united-manufacturing-hub/ManagementConsole/pull/759
> feat: 0.2.18

- umh.docs.umh.app/content/en/docs/features/_index.md
- umh.docs.umh.app/content/en/docs/features/devicecontainerinfrastructure/umh-lite.md
- Fixes https://github.com/united-manufacturing-hub/MgmtIssues/issues/1778
> Add page for UMH lite

- .github/workflows/update-search.yaml
This pr migrates the search to typesense cloud.
Repo secret was already updated
> Switch to typesense cloud

- umh.docs.umh.app/static/js/search.js
part 2, as i forgot to commit this earlier
> use new api for search

- umh.docs.umh.app/content/en/docs/getstarted/installation.md
Fixes: ENG-636
Fixes: https://github.com/united-manufacturing-hub/umh.docs.umh.app/issues/143
> ENG-636 Add ubuntu special req, and SSE

- umh.docs.umh.app/content/en/docs/production-guide/upgrading/0.10.6.md
- umh.docs.umh.app/content/en/docs/production-guide/upgrading/0.13.7.md
- umh.docs.umh.app/content/en/docs/production-guide/upgrading/0.14.0.md
> ENG-653 migration guide for 0.14.0

- umh.docs.umh.app/content/en/docs/features/connectivity/_index.md
- umh.docs.umh.app/content/en/docs/getstarted/dataacquisitionmanipulation.md
- umh.docs.umh.app/content/en/docs/getstarted/managingthesystem.md
- umh.docs.umh.app/static/images/getstarted/dataAcquisitionManipulation/addConnectionDetails.png
- umh.docs.umh.app/static/images/getstarted/dataAcquisitionManipulation/connectionManagement.png
- umh.docs.umh.app/static/images/getstarted/dataAcquisitionManipulation/protocolConverters.png
- umh.docs.umh.app/static/images/getstarted/dataAcquisitionManipulation/tagBrowserHumidity.png
- umh.docs.umh.app/static/images/getstarted/dataAcquisitionManipulation/tagBrowserTemperature.png
- umh.docs.umh.app/static/images/getstarted/managingTheSystem/componentView.png
This PR updates some of the wording:
- Data Sources -> Protocol Converters
- Connections -> Network Device/Service
- Connection Management -> Protocol Converters (tab)
And mentions the Universal Protocol Converter feature in the [Data Acquisition and Manipulation](https://umh.docs.umh.app/docs/getstarted/dataacquisitionmanipulation/) page.
- Fixes ENG-429
Same as in https://github.com/united-manufacturing-hub/umh.docs.umh.app/pull/292
> Update get started guide wording and mention Universal Protocol Converter feature

- umh.docs.umh.app/content/en/docs/datamodel/database/_index.md
- umh.docs.umh.app/content/en/docs/datamodel/database/historian/_historian.md
- umh.docs.umh.app/content/en/docs/features/datainfrastructure/historian.md
- umh.docs.umh.app/content/en/docs/features/datainfrastructure/postgresql_and_grafana_alerts.md
- umh.docs.umh.app/content/en/docs/getstarted/datavisualization.md
Do not merge/release until https://github.com/united-manufacturing-hub/united-manufacturing-hub/pull/1802 is released
> ENG-712 document new funcs

- umh.docs.umh.app/content/en/docs/getstarted/managingthesystem.md
The PR fixes the broken link on the `Datamodels` hyperlink shown in the following image [Documentation Link here](https://umh.docs.umh.app/docs/getstarted/managingthesystem/)
> [ENG-1173] Fix the broken hyperlink for Datamodels

- umh.docs.umh.app/content/en/docs/production-guide/upgrading/0.16.0.md
Add upgrade notes for umh version 0.16.0
> [ENG-1400] Add documentation to upgrade to v0.16.0
